USE vk;

DROP TABLE IF EXISTS post;
CREATE TABLE post(
	id SERIAL,
	autor_id BIGINT UNSIGNED NOT NULL,
	media_id BIGINT UNSIGNED,
	created_at DATETIME DEFAULT NOW(),
	
	FOREIGN KEY (autor_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (media_id) REFERENCES media(id) ON UPDATE CASCADE ON DELETE SET NULL
);

DROP TABLE IF EXISTS reposts;
CREATE TABLE reposts(
	id SERIAL,
	post_id BIGINT UNSIGNED NOT NULL,
	repost_autor_id BIGINT UNSIGNED NOT NULL,
	created_at DATETIME DEFAULT NOW(),
	
	FOREIGN KEY (post_id) REFERENCES post(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (repost_autor_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);


DROP TABLE IF EXISTS comments;
CREATE TABLE comments(
	id SERIAL,
	autor_id BIGINT UNSIGNED NOT NULL, 
	post_id BIGINT UNSIGNED NOT NULL,
	created_at DATETIME DEFAULT now() ON UPDATE now(),
-- 	PRIMARY KEY (autor_id, media_id) # может быть несколько комментов от одного автора
	
	FOREIGN KEY (autor_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (post_id) REFERENCES post(id) ON UPDATE CASCADE ON DELETE CASCADE
);

